name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: prereq
      run: |
           sudo apt-get update
           sudo apt-get install libfuse-dev
    - name: Build
      run: cargo build --verbose
    - name: Build docs
      run: cargo doc
    - name: Run tests
      run: cargo test --verbose
    - name: Archive debug artifacts
      uses: actions/upload-artifact@v2
      with:
          name: dist
          path: |
            target/debug
    - name: Archive docs artifacts
      uses: actions/upload-artifact@v2
      with:
          name: doc
          path: |
            target/doc
